"""update_interview_status_enum_with_completed

Revision ID: 89258c225854
Revises: 001
Create Date: 2025-08-31 15:47:11.246566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89258c225854'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'metadata')
    op.drop_constraint(op.f('user_page_access_user_id_page_name_key'), 'user_page_access', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_page_access_user_id_page_name_key'), 'user_page_access', ['user_id', 'page_name'], postgresql_nulls_not_distinct=False)
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
